In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [26]:
idnt = pd.read_csv('IDENTITY_fill.csv')

In [27]:
idnt = idnt.dropna(subset=['female'])

In [32]:
idnt = idnt[idnt['target'].isnull()]

In [33]:
idnt

,id,comment_text,toxicity,severe_toxicity,obscene,threat,insult,identity_attack,sexual_explicit,female,male,christian,white,muslim,black,homosexual_gay_or_lesbian,jewish,psychiatric_or_mental_illness,asian,target
1,0,"No, we need Trump to stay in so he can lose.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000038,0.000084,0.000052,0.000019,0.000028,0.000016,0.000008,0.000007,0.000009,0.000009,NaN
2,1,Wow. Precious.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000061,0.000074,0.000058,0.000021,0.000023,0.000013,0.000007,0.000006,0.000010,0.000008,NaN
7,4,"When it hit and run, then the word ""accident"" ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000046,0.000067,0.000069,0.000021,0.000027,0.000016,0.000009,0.000007,0.000008,0.000008,NaN
8,5,Baloney.\nThese were GOP that wanted to vote i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000030,0.000083,0.000050,0.000024,0.000022,0.000025,0.000010,0.000009,0.000011,0.000011,NaN
11,6,"China is building ""railways in Africa"" ...yep ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000100,0.000450,0.000276,0.000485,0.000153,0.000824,0.000156,0.000106,0.038735,0.000403,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1818185,1068575,Just so long as the policemen in your argument...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000050,0.000897,0.000111,0.000169,0.000179,0.000473,0.000054,0.000094,0.000118,0.014648,NaN
1818187,1068576,"Wow, not a mention of 8 long years of Obama's ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000030,0.000074,0.000071,0.000021,0.000019,0.000025,0.000010,0.000008,0.000015,0.000010,NaN
1818189,1068577,Look at American history and one will see that...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000048,0.000127,0.000056,0.000016,0.000025,0.000015,0.000007,0.000007,0.000008,0.000009,NaN
1818195,1068581,"Too lenient. Considering her crimes, Mansfield...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000056,0.000073,0.000096,0.000015,0.000018,0.000013,0.000011,0.000008,0.000012,0.000008,NaN
1818197,1068582,Congratulations Elvi! I know you will do us p...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000055,0.000061,0.000077,0.000020,0.000022,0.000013,0.000009,0.000007,0.000009,0.000008,NaN

1068585

In [4]:
path = '/home/Kaggle-challenge/workspace/data/'


train = pd.read_csv(path + 'train.csv')
test = pd.read_csv(path + 'test.csv')

In [52]:
train_n = train.dropna()
test_d = train[~train.index.isin(train_n.index)]
test_d = test_d.reset_index(drop=True)

In [53]:
col = ['female',
       'male', 'christian', 'white', 'muslim', 'black',
       'homosexual_gay_or_lesbian', 'jewish', 'psychiatric_or_mental_illness',
       'asian']

for i in col:
    test_d[i].fillna(idnt[i], inplace=True)

/tmp/ipykernel_101156/427030456.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  test_d[i].fillna(idnt[i], inplace=True)

In [48]:
idnt = idnt.reset_index(drop=True)
idnt

,id,comment_text,toxicity,severe_toxicity,obscene,threat,insult,identity_attack,sexual_explicit,female,male,christian,white,muslim,black,homosexual_gay_or_lesbian,jewish,psychiatric_or_mental_illness,asian,target
0,0,"No, we need Trump to stay in so he can lose.",NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000038,0.000084,0.000052,0.000019,0.000028,0.000016,0.000008,0.000007,0.000009,0.000009,NaN
1,1,Wow. Precious.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000061,0.000074,0.000058,0.000021,0.000023,0.000013,0.000007,0.000006,0.000010,0.000008,NaN
2,4,"When it hit and run, then the word ""accident"" ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000046,0.000067,0.000069,0.000021,0.000027,0.000016,0.000009,0.000007,0.000008,0.000008,NaN
3,5,Baloney.\nThese were GOP that wanted to vote i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000030,0.000083,0.000050,0.000024,0.000022,0.000025,0.000010,0.000009,0.000011,0.000011,NaN
4,6,"China is building ""railways in Africa"" ...yep ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000100,0.000450,0.000276,0.000485,0.000153,0.000824,0.000156,0.000106,0.038735,0.000403,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
749610,1068575,Just so long as the policemen in your argument...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000050,0.000897,0.000111,0.000169,0.000179,0.000473,0.000054,0.000094,0.000118,0.014648,NaN
749611,1068576,"Wow, not a mention of 8 long years of Obama's ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000030,0.000074,0.000071,0.000021,0.000019,0.000025,0.000010,0.000008,0.000015,0.000010,NaN
749612,1068577,Look at American history and one will see that...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000048,0.000127,0.000056,0.000016,0.000025,0.000015,0.000007,0.000007,0.000008,0.000009,NaN
749613,1068581,"Too lenient. Considering her crimes, Mansfield...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000056,0.000073,0.000096,0.000015,0.000018,0.000013,0.000011,0.000008,0.000012,0.000008,NaN
749614,1068582,Congratulations Elvi! I know you will do us p...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000055,0.000061,0.000077,0.000020,0.000022,0.000013,0.000009,0.000007,0.000009,0.000008,NaN

In [55]:
tmp = pd.concat([test_d,train_n],axis=0)

In [59]:
tmp.to_csv('IDENTITY_fill.csv', index=False)

In [60]:
wewe = pd.read_csv('IDENTITY_fill.csv')
wewe

,id,comment_text,toxicity,severe_toxicity,obscene,threat,insult,identity_attack,sexual_explicit,female,male,christian,white,muslim,black,homosexual_gay_or_lesbian,jewish,psychiatric_or_mental_illness,asian
0,0,"No, we need Trump to stay in so he can lose.",0.166667,0.0,0.0,0.0,0.166667,0.0,0.0,0.000038,0.000084,0.000052,0.000019,0.000028,0.000016,0.000008,0.000007,0.000009,0.000009
1,1,Wow. Precious.,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000061,0.000074,0.000058,0.000021,0.000023,0.000013,0.000007,0.000006,0.000010,0.000008
2,4,"When it hit and run, then the word ""accident"" ...",0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000046,0.000067,0.000069,0.000021,0.000027,0.000016,0.000009,0.000007,0.000008,0.000008
3,5,Baloney.\nThese were GOP that wanted to vote i...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000030,0.000083,0.000050,0.000024,0.000022,0.000025,0.000010,0.000009,0.000011,0.000011
4,6,"China is building ""railways in Africa"" ...yep ...",0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000100,0.000450,0.000276,0.000485,0.000153,0.000824,0.000156,0.000106,0.038735,0.000403
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1068580,1068578,Don't expect the Alaskan budget problem to go ...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1068581,1068579,"And two priests already on this thread, from w...",0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.200000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1068582,1068580,"Ken_Conklin, You have your views about churche...",0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1068583,1068583,"""The problem appears real, and not confined to...",0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1068584,1068584,The postman was white?,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000,0.166667,0.000000,0.833333,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [58]:
train

,id,comment_text,toxicity,severe_toxicity,obscene,threat,insult,identity_attack,sexual_explicit,female,male,christian,white,muslim,black,homosexual_gay_or_lesbian,jewish,psychiatric_or_mental_illness,asian
0,0,"No, we need Trump to stay in so he can lose.",0.166667,0.0,0.0,0.0,0.166667,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Wow. Precious.,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Haven't been here when the oil economy dead ha...,0.200000,0.0,0.0,0.2,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
3,3,'\nBaloney.,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
4,4,"When it hit and run, then the word ""accident"" ...",0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1068580,1068580,"Ken_Conklin, You have your views about churche...",0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
1068581,1068581,"Too lenient. Considering her crimes, Mansfield...",0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1068582,1068582,Congratulations Elvi! I know you will do us p...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1068583,1068583,"""The problem appears real, and not confined to...",0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
1068584,1068584,The postman was white?,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.166667,0.0,0.833333,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
train_n = train.dropna()
test_d = train[~train.index.isin(train_n.index)][['id','comment_text']]
test_d

              id                                       comment_text
0              0       No, we need Trump to stay in so he can lose.
1              1                                    Wow.  Precious.
4              4  When it hit and run, then the word "accident" ...
5              5  Baloney.\nThese were GOP that wanted to vote i...
6              6  China is building "railways in Africa" ...yep ...
...          ...                                                ...
1068575  1068575  Just so long as the policemen in your argument...
1068576  1068576  Wow, not a mention of 8 long years of Obama's ...
1068577  1068577  Look at American history and one will see that...
1068581  1068581  Too lenient. Considering her crimes, Mansfield...
1068582  1068582  Congratulations Elvi!  I know you will do us p...

[749615 rows x 2 columns]

In [7]:
test_d['sldl'] = 1

In [8]:
test_d

              id                                       comment_text  sldl
0              0       No, we need Trump to stay in so he can lose.     1
1              1                                    Wow.  Precious.     1
4              4  When it hit and run, then the word "accident" ...     1
5              5  Baloney.\nThese were GOP that wanted to vote i...     1
6              6  China is building "railways in Africa" ...yep ...     1
...          ...                                                ...   ...
1068575  1068575  Just so long as the policemen in your argument...     1
1068576  1068576  Wow, not a mention of 8 long years of Obama's ...     1
1068577  1068577  Look at American history and one will see that...     1
1068581  1068581  Too lenient. Considering her crimes, Mansfield...     1
1068582  1068582  Congratulations Elvi!  I know you will do us p...     1

[749615 rows x 3 columns]

In [ ]:
train[(train['toxicity'] < 0.1) & (train['identity_attack'] <0.05)]['comment_text'].tolist()

In [40]:
train[(train['toxicity'] >= 0.9) & (train['identity_attack'] >=0.8)]['comment_text'][1055816]

"Jolly Old London town. If the food doesn't kill you, the immigrants will."

In [50]:
train[(train['toxicity'] >= 0.9) & (train['identity_attack'] <0.05)]['comment_text'][1067587]

'Hang the drug dealers !!'

In [5]:
temp = train[train['female'].notnull()]

In [7]:
temp.info()

<class 'pandas.core.frame.DataFrame'>
Index: 318970 entries, 2 to 1068584
Data columns (total 19 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   id                             318970 non-null  int64
 1   comment_text                   318970 non-null  object
 2   toxicity                       318970 non-null  float64
 3   severe_toxicity                318970 non-null  float64
 4   obscene                        318970 non-null  float64
 5   threat                         318970 non-null  float64
 6   insult                         318970 non-null  float64
 7   identity_attack                318970 non-null  float64
 8   sexual_explicit                318970 non-null  float64
 9   female                         318970 non-null  float64
 10  male                           318970 non-null  float64
 11  christian                      318970 non-null  float64
 12  white                          318970 non-null  float64
 13  muslim                         318970 non-null  float64
 14  black                          318970 non-null  float64
 15  homosexual_gay_or_lesbian      318970 non-null  float64
 16  jewish                         318970 non-null  float64
 17  psychiatric_or_mental_illness  318970 non-null  float64
 18  asian                          318970 non-null  float64
dtypes: float64(17), int64(1), object(1)
memory usage: 48.7+ MB

In [9]:
col = ['female','male', 'christian', 'white', 'muslim', 'black',
       'homosexual_gay_or_lesbian', 'jewish', 'psychiatric_or_mental_illness',
       'asian']

In [46]:
subgroup = train[(train['female'] >= 0.5) | (train['male'] >= 0.5) | (train['christian'] >= 0.5) | (train['white'] >= 0.5) | (train['muslim'] >= 0.5) | (train['black'] >= 0.5) | (train['homosexual_gay_or_lesbian'] >= 0.5) | (train['jewish'] >= 0.5) | (train['psychiatric_or_mental_illness'] >= 0.5) | (train['asian'] >= 0.5)]
subgroup

,id,comment_text,toxicity,severe_toxicity,obscene,threat,insult,identity_attack,sexual_explicit,female,male,christian,white,muslim,black,homosexual_gay_or_lesbian,jewish,psychiatric_or_mental_illness,asian
11,11,"Well, when you consider the success of Playboy...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000
22,22,You seem to be ignorant of the fact that the I...,0.6,0.0,0.0,0.0,0.6,0.2,0.0,0.4,0.000000,0.0,0.000000,0.9,0.0,0.0,0.0,0.0,0.000000
37,37,What do Christians have to do with this articl...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000
59,59,Hillary will meet the requirements of her fund...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.6,0.100000,0.0,0.000000,0.0,0.0,0.2,0.0,0.0,0.000000
66,66,"Many couples incorporate the above mentioned ""...",0.1,0.0,0.1,0.0,0.0,0.0,0.2,0.0,0.700000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1068545,1068545,"In a recent highly publicised case, the man in...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000
1068546,1068546,https://www.youtube.com/watch?v=Qup47XJGIl4\n\...,0.3,0.0,0.0,0.2,0.1,0.1,0.0,0.0,1.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000
1068556,1068556,Liu Xiaobo is too famous. If he was able to tr...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.5,0.0,0.0,0.0,0.833333
1068572,1068572,Well aren't you our Debbie Downer? You must be...,0.2,0.0,0.0,0.0,0.2,0.0,0.0,1.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000
1068584,1068584,The postman was white?,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.166667,0.0,0.833333,0.0,0.0,0.0,0.0,0.0,0.000000

In [47]:
background = train[~((train['female'] >= 0.5) | (train['male'] >= 0.5) | (train['christian'] >= 0.5) | (train['white'] >= 0.5) | (train['muslim'] >= 0.5) | (train['black'] >= 0.5) | (train['homosexual_gay_or_lesbian'] >= 0.5) | (train['jewish'] >= 0.5) | (train['psychiatric_or_mental_illness'] >= 0.5) | (train['asian'] >= 0.5))]

In [48]:
background

,id,comment_text,toxicity,severe_toxicity,obscene,threat,insult,identity_attack,sexual_explicit,female,male,christian,white,muslim,black,homosexual_gay_or_lesbian,jewish,psychiatric_or_mental_illness,asian
0,0,"No, we need Trump to stay in so he can lose.",0.166667,0.0,0.0,0.0,0.166667,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Wow. Precious.,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Haven't been here when the oil economy dead ha...,0.200000,0.0,0.0,0.2,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,'\nBaloney.,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,"When it hit and run, then the word ""accident"" ...",0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1068579,1068579,"And two priests already on this thread, from w...",0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1068580,1068580,"Ken_Conklin, You have your views about churche...",0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1068581,1068581,"Too lenient. Considering her crimes, Mansfield...",0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1068582,1068582,Congratulations Elvi! I know you will do us p...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1068583,1068583,"""The problem appears real, and not confined to...",0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [21]:
BP = background[background['toxicity'] >=0.5]
BN = background[background['toxicity'] <0.5]
SP = subgroup[subgroup['toxicity'] >= 0.5]
SN = subgroup[subgroup['toxicity'] < 0.5]

In [26]:
sensitivity = len(BP)/(len(BP) + len(SP)) # 악성중 진짜 악성
specificity = len(BN)/(len(SN) + len(BN)) # 악성x중 진짜 악성x

In [27]:
f"Sensitivity:  {sensitivity}, Specificity: {specificity}"

'Sensitivity:  0.8087860071442398, Specificity: 0.8854781569690667'

In [28]:
len(BP) + len(SN), len(BN)+ len(SP)

(201285, 867300)

In [32]:
background

,id,comment_text,toxicity,severe_toxicity,obscene,threat,insult,identity_attack,sexual_explicit,female,male,christian,white,muslim,black,homosexual_gay_or_lesbian,jewish,psychiatric_or_mental_illness,asian
0,0,"No, we need Trump to stay in so he can lose.",0.166667,0.0,0.0,0.0,0.166667,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Wow. Precious.,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Haven't been here when the oil economy dead ha...,0.200000,0.0,0.0,0.2,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,'\nBaloney.,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,"When it hit and run, then the word ""accident"" ...",0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1068579,1068579,"And two priests already on this thread, from w...",0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1068580,1068580,"Ken_Conklin, You have your views about churche...",0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1068581,1068581,"Too lenient. Considering her crimes, Mansfield...",0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1068582,1068582,Congratulations Elvi! I know you will do us p...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1068583,1068583,"""The problem appears real, and not confined to...",0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [34]:
937492 + 109360

1046852

In [35]:
t = pd.concat([background, SN],axis=0)

t

,id,comment_text,toxicity,severe_toxicity,obscene,threat,insult,identity_attack,sexual_explicit,female,male,christian,white,muslim,black,homosexual_gay_or_lesbian,jewish,psychiatric_or_mental_illness,asian
0,0,"No, we need Trump to stay in so he can lose.",0.166667,0.0,0.0,0.0,0.166667,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Wow. Precious.,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Haven't been here when the oil economy dead ha...,0.200000,0.0,0.0,0.2,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000
3,3,'\nBaloney.,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000
4,4,"When it hit and run, then the word ""accident"" ...",0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1068545,1068545,"In a recent highly publicised case, the man in...",0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,1.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000
1068546,1068546,https://www.youtube.com/watch?v=Qup47XJGIl4\n\...,0.300000,0.0,0.0,0.2,0.100000,0.1,0.0,0.0,1.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000
1068556,1068556,Liu Xiaobo is too famous. If he was able to tr...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.5,0.0,0.0,0.0,0.833333
1068572,1068572,Well aren't you our Debbie Downer? You must be...,0.200000,0.0,0.0,0.0,0.200000,0.0,0.0,1.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000
1068584,1068584,The postman was white?,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.166667,0.0,0.833333,0.0,0.0,0.0,0.0,0.0,0.000000

In [36]:
train

,id,comment_text,toxicity,severe_toxicity,obscene,threat,insult,identity_attack,sexual_explicit,female,male,christian,white,muslim,black,homosexual_gay_or_lesbian,jewish,psychiatric_or_mental_illness,asian
0,0,"No, we need Trump to stay in so he can lose.",0.166667,0.0,0.0,0.0,0.166667,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Wow. Precious.,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Haven't been here when the oil economy dead ha...,0.200000,0.0,0.0,0.2,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
3,3,'\nBaloney.,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
4,4,"When it hit and run, then the word ""accident"" ...",0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1068580,1068580,"Ken_Conklin, You have your views about churche...",0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
1068581,1068581,"Too lenient. Considering her crimes, Mansfield...",0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1068582,1068582,Congratulations Elvi! I know you will do us p...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1068583,1068583,"""The problem appears real, and not confined to...",0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
1068584,1068584,The postman was white?,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.166667,0.0,0.833333,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
train = train[['comment_text','toxicity', 'severe_toxicity']]

train.head()

,comment_text,toxicity,severe_toxicity
0,"No, we need Trump to stay in so he can lose.",0.166667,0.0
1,Wow. Precious.,0.000000,0.0
2,Haven't been here when the oil economy dead ha...,0.200000,0.0
3,'\nBaloney.,0.000000,0.0
4,"When it hit and run, then the word ""accident"" ...",0.000000,0.0

In [14]:
col = ['toxicity', 'severe_toxicity', 'obscene',
       'threat', 'insult', 'identity_attack', 'sexual_explicit']


train = train[col]

In [16]:
for i in col:
    train[i] = (train[i] >= 0.5).astype(int)

In [29]:
background

,id,comment_text,toxicity,severe_toxicity,obscene,threat,insult,identity_attack,sexual_explicit,female,male,christian,white,muslim,black,homosexual_gay_or_lesbian,jewish,psychiatric_or_mental_illness,asian
0,0,"No, we need Trump to stay in so he can lose.",0.166667,0.0,0.0,0.0,0.166667,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Wow. Precious.,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Haven't been here when the oil economy dead ha...,0.200000,0.0,0.0,0.2,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,'\nBaloney.,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,"When it hit and run, then the word ""accident"" ...",0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1068579,1068579,"And two priests already on this thread, from w...",0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1068580,1068580,"Ken_Conklin, You have your views about churche...",0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1068581,1068581,"Too lenient. Considering her crimes, Mansfield...",0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1068582,1068582,Congratulations Elvi! I know you will do us p...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1068583,1068583,"""The problem appears real, and not confined to...",0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [29]:
lst = []
for i in range(len(train)):
    lst.append(train.iloc[i,:].tolist())
    
train['target'] = lst

In [31]:
train['target'] = lst

,toxicity,severe_toxicity,obscene,threat,insult,identity_attack,sexual_explicit,target
8,1,0,0,0,0,0,0,"[1, 0, 0, 0, 0, 0, 0]"
15,1,0,0,0,1,0,0,"[1, 0, 0, 0, 1, 0, 0]"
22,1,0,0,0,1,0,0,"[1, 0, 0, 0, 1, 0, 0]"
25,1,0,0,0,1,0,0,"[1, 0, 0, 0, 1, 0, 0]"
40,1,0,0,0,1,0,0,"[1, 0, 0, 0, 1, 0, 0]"
...,...,...,...,...,...,...,...,...
1068494,1,0,0,0,1,0,0,"[1, 0, 0, 0, 1, 0, 0]"
1068512,1,0,0,0,1,0,0,"[1, 0, 0, 0, 1, 0, 0]"
1068514,1,0,0,0,0,1,0,"[1, 0, 0, 0, 0, 1, 0]"
1068518,1,0,0,0,1,0,0,"[1, 0, 0, 0, 1, 0, 0]"
1068566,1,0,0,0,0,0,0,"[1, 0, 0, 0, 0, 0, 0]"

In [5]:
train[(train['identity_attack']<=0.5) & (train['toxicity']>=0.5)]

,id,comment_text,toxicity,severe_toxicity,obscene,threat,insult,identity_attack,sexual_explicit,female,male,christian,white,muslim,black,homosexual_gay_or_lesbian,jewish,psychiatric_or_mental_illness,asian
8,8,There's currently a skills shortage problem in...,0.600000,0.000000,0.400000,0.000000,0.400000,0.200000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,15,Does the Magna Carta also require that Western...,0.700000,0.000000,0.300000,0.000000,0.500000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,22,You seem to be ignorant of the fact that the I...,0.600000,0.000000,0.000000,0.000000,0.600000,0.200000,0.000000,0.4,0.0,0.0,0.0,0.9,0.0,0.0,0.0,0.0,0.0
25,25,Newsflash....the 2nd Amendment does not apply ...,0.684211,0.000000,0.035088,0.000000,0.701754,0.017544,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,40,"""Gardner, speaking to KMGH-Channel 7, also sai...",0.600000,0.000000,0.000000,0.000000,0.600000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1068494,1068494,Because you are that stupid.,0.973684,0.026316,0.131579,0.000000,0.921053,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1068512,1068512,"Roy Moore, Strong candidate for most disgustin...",0.500000,0.100000,0.000000,0.000000,0.500000,0.000000,0.000000,0.0,0.2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1068514,1068514,Another angry/mentally ill white guy with a gu...,0.600000,0.100000,0.000000,0.000000,0.400000,0.500000,0.000000,0.0,0.4,0.0,0.8,0.0,0.0,0.1,0.0,0.6,0.0
1068518,1068518,"Plainthinker, being the parasite that he is I ...",0.754098,0.032787,0.114754,0.000000,0.737705,0.000000,0.016393,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1068566,1068566,Whoever thinks this should have been handled d...,0.500000,0.028571,0.128571,0.085714,0.485714,0.028571,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
train[(train['identity_attack']>=0.5) & (train['toxicity']<=0.5)]

,id,comment_text,toxicity,severe_toxicity,obscene,threat,insult,identity_attack,sexual_explicit,female,male,christian,white,muslim,black,homosexual_gay_or_lesbian,jewish,psychiatric_or_mental_illness,asian
602,602,What I fail to understand is how calling someo...,0.5,0.0,0.0,0.0,0.2,0.5,0.1,0.0,0.0,0.0,0.0,0.0,0.00,1.0,0.0,0.0,0.0
973,973,"""Unfortunately a lot of diseases can spread th...",0.3,0.1,0.0,0.0,0.0,0.5,0.1,0.0,0.0,0.0,0.0,0.0,0.00,1.0,0.0,0.0,0.0
1266,1266,.....and that alt-leftist grabbed that guy's s...,0.5,0.0,0.0,0.2,0.3,0.5,0.0,0.0,0.8,0.0,1.0,0.0,0.00,0.0,0.0,0.0,0.0
1503,1503,Funny that you haven't mentioned the Viagra or...,0.5,0.1,0.0,0.0,0.2,0.5,0.2,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0
2046,2046,And the Indian invaders took the country from ...,0.5,0.0,0.0,0.0,0.1,0.5,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1066858,1066858,Terrorist acts against Muslims and non-Muslims...,0.5,0.0,0.0,0.0,0.2,0.5,0.0,0.0,0.2,1.0,0.0,1.0,0.00,0.0,0.0,0.0,0.0
1066918,1066918,"Spencer is just a white version of BLM, our bl...",0.5,0.0,0.0,0.0,0.4,0.5,0.0,0.0,0.0,0.0,1.0,0.0,0.75,0.0,0.0,0.0,0.0
1067208,1067208,It's curious how the liberal media continually...,0.4,0.0,0.0,0.0,0.2,0.5,0.0,0.0,0.5,0.0,1.0,0.0,0.80,0.2,0.0,0.0,0.0
1067805,1067805,The Chinese Emperors were a pretty vicious lot.,0.5,0.0,0.0,0.0,0.3,0.5,0.0,0.0,0.1,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.4
1068363,1068363,And what about the gross entitlement of settle...,0.5,0.0,0.0,0.0,0.4,0.5,0.0,0.0,0.0,0.0,1.0,0.0,0.00,0.0,0.0,0.0,0.0

In [4]:
test

            id                                       comment_text
0            0  Not me - I've seen investigations into trainin...
1            1  She was fully deportable and I am glad someone...
2            2                   That's for the courts to decide.
3            3  When she was a scrawny 11-year-old, Sherry Joh...
4            4  I cannot help but wonder what Mueller is findi...
...        ...                                                ...
431410  431410  What would you propose France should do to rid...
431411  431411  The article was about Hoodoo, and the criteria...
431412  431412  Apparently, according to numerous nationwide w...
431413  431413  Obama on the United States as a Christian nati...
431414  431414  Maybe. On the basis of "size of problem," yeah...

[431415 rows x 2 columns]

In [7]:
submission

NameError: name 'submission' is not defined

In [6]:
tmp = pd.DataFrame({"id": test['id'], 'prediction':1})

In [7]:
tmp

            id  prediction
0            0           1
1            1           1
2            2           1
3            3           1
4            4           1
...        ...         ...
431410  431410           1
431411  431411           1
431412  431412           1
431413  431413           1
431414  431414           1

[431415 rows x 2 columns]

In [3]:
background = train[train['toxicity'] >= 0.5]

In [4]:
background

,id,comment_text,toxicity,severe_toxicity,obscene,threat,insult,identity_attack,sexual_explicit,female,male,christian,white,muslim,black,homosexual_gay_or_lesbian,jewish,psychiatric_or_mental_illness,asian
8,8,There's currently a skills shortage problem in...,0.600000,0.000000,0.400000,0.000000,0.400000,0.200000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,15,Does the Magna Carta also require that Western...,0.700000,0.000000,0.300000,0.000000,0.500000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,22,You seem to be ignorant of the fact that the I...,0.600000,0.000000,0.000000,0.000000,0.600000,0.200000,0.000000,0.4,0.0,0.0,0.0,0.9,0.0,0.0,0.0,0.0,0.0
25,25,Newsflash....the 2nd Amendment does not apply ...,0.684211,0.000000,0.035088,0.000000,0.701754,0.017544,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,40,"""Gardner, speaking to KMGH-Channel 7, also sai...",0.600000,0.000000,0.000000,0.000000,0.600000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1068494,1068494,Because you are that stupid.,0.973684,0.026316,0.131579,0.000000,0.921053,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1068512,1068512,"Roy Moore, Strong candidate for most disgustin...",0.500000,0.100000,0.000000,0.000000,0.500000,0.000000,0.000000,0.0,0.2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1068514,1068514,Another angry/mentally ill white guy with a gu...,0.600000,0.100000,0.000000,0.000000,0.400000,0.500000,0.000000,0.0,0.4,0.0,0.8,0.0,0.0,0.1,0.0,0.6,0.0
1068518,1068518,"Plainthinker, being the parasite that he is I ...",0.754098,0.032787,0.114754,0.000000,0.737705,0.000000,0.016393,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1068566,1068566,Whoever thinks this should have been handled d...,0.500000,0.028571,0.128571,0.085714,0.485714,0.028571,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
IDENTITY_COLMUNS = [
    'female','male', 'christian', 'white', 'muslim', 'black',
    'homosexual_gay_or_lesbian', 'jewish', 'psychiatric_or_mental_illness', 'asian'
]

In [18]:
background[(background[IDENTITY_COLMUNS] != 0)& background[IDENTITY_COLMUNS].notna()]

,id,comment_text,toxicity,severe_toxicity,obscene,threat,insult,identity_attack,sexual_explicit,female,male,christian,white,muslim,black,homosexual_gay_or_lesbian,jewish,psychiatric_or_mental_illness,asian
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.4,NaN,NaN,NaN,0.9,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1068494,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1068512,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.2,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
1068514,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.4,NaN,0.8,NaN,NaN,0.1,NaN,0.6,NaN
1068518,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1068566,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
idnty =background[IDENTITY_COLMUNS]
idnty

,female,male,christian,white,muslim,black,homosexual_gay_or_lesbian,jewish,psychiatric_or_mental_illness,asian
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,0.4,0.0,0.0,0.0,0.9,0.0,0.0,0.0,0.0,0.0
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...
1068494,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1068512,0.0,0.2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1068514,0.0,0.4,0.0,0.8,0.0,0.0,0.1,0.0,0.6,0.0
1068518,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1068566,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
background

,id,comment_text,toxicity,severe_toxicity,obscene,threat,insult,identity_attack,sexual_explicit,female,male,christian,white,muslim,black,homosexual_gay_or_lesbian,jewish,psychiatric_or_mental_illness,asian
8,8,There's currently a skills shortage problem in...,0.600000,0.000000,0.400000,0.000000,0.400000,0.200000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,15,Does the Magna Carta also require that Western...,0.700000,0.000000,0.300000,0.000000,0.500000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,22,You seem to be ignorant of the fact that the I...,0.600000,0.000000,0.000000,0.000000,0.600000,0.200000,0.000000,0.4,0.0,0.0,0.0,0.9,0.0,0.0,0.0,0.0,0.0
25,25,Newsflash....the 2nd Amendment does not apply ...,0.684211,0.000000,0.035088,0.000000,0.701754,0.017544,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,40,"""Gardner, speaking to KMGH-Channel 7, also sai...",0.600000,0.000000,0.000000,0.000000,0.600000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1068494,1068494,Because you are that stupid.,0.973684,0.026316,0.131579,0.000000,0.921053,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1068512,1068512,"Roy Moore, Strong candidate for most disgustin...",0.500000,0.100000,0.000000,0.000000,0.500000,0.000000,0.000000,0.0,0.2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1068514,1068514,Another angry/mentally ill white guy with a gu...,0.600000,0.100000,0.000000,0.000000,0.400000,0.500000,0.000000,0.0,0.4,0.0,0.8,0.0,0.0,0.1,0.0,0.6,0.0
1068518,1068518,"Plainthinker, being the parasite that he is I ...",0.754098,0.032787,0.114754,0.000000,0.737705,0.000000,0.016393,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1068566,1068566,Whoever thinks this should have been handled d...,0.500000,0.028571,0.128571,0.085714,0.485714,0.028571,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
x = background.loc[22]['comment_text']

In [32]:
x

"You seem to be ignorant of the fact that the Islamic world is incredibly diverse, with innumerable sects, traditions, and peoples. The Quebec law targets only the most extreme and retrograde sects of the religion, such as Wahhabism, where covering the face of women is still prescribed. \n\nThis country needs a more nuanced debate on multiculturalism where we don't treat each large ethnic group, including a group as diverse as Muslim Canadians, as a single, monolithic entity. Things are much more complicated, but unfortunately journalists and activists are either too lazy or unscrupulous to be honest about the complexity of these issues. \n\nThe picture painted by this article and many news commentators is that all Muslims, including let's say a North African moderate Muslim, condone and support all expressions of their religion, including the form of Islam propounded by the Taliban in Afghanistan. This is a ridiculous point of view."

In [33]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1068585 entries, 0 to 1068584
Data columns (total 19 columns):
 #   Column                         Non-Null Count    Dtype
---  ------                         --------------    -----
 0   id                             1068585 non-null  int64
 1   comment_text                   1068585 non-null  object
 2   toxicity                       1068585 non-null  float64
 3   severe_toxicity                1068585 non-null  float64
 4   obscene                        1068585 non-null  float64
 5   threat                         1068585 non-null  float64
 6   insult                         1068585 non-null  float64
 7   identity_attack                1068585 non-null  float64
 8   sexual_explicit                1068585 non-null  float64
 9   female                         318970 non-null   float64
 10  male                           318970 non-null   float64
 11  christian                      318970 non-null   float64
 12  white                          318970 non-null   float64
 13  muslim                         318970 non-null   float64
 14  black                          318970 non-null   float64
 15  homosexual_gay_or_lesbian      318970 non-null   float64
 16  jewish                         318970 non-null   float64
 17  psychiatric_or_mental_illness  318970 non-null   float64
 18  asian                          318970 non-null   float64
dtypes: float64(17), int64(1), object(1)
memory usage: 154.9+ MB

애초에 학습시키는 정보에 대해서는 비어있는 값이 없다.

In [47]:
No_IDNT = [ 'comment_text', 'severe_toxicity', 'obscene',
       'threat', 'insult', 'identity_attack', 'sexual_explicit','t`oxicity']

train_df = train[No_IDNT]

In [48]:
train_df

,comment_text,severe_toxicity,obscene,threat,insult,identity_attack,sexual_explicit,toxicity
0,"No, we need Trump to stay in so he can lose.",0.0,0.0,0.0,0.166667,0.0,0.0,0.166667
1,Wow. Precious.,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000
2,Haven't been here when the oil economy dead ha...,0.0,0.0,0.2,0.000000,0.0,0.0,0.200000
3,'\nBaloney.,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000
4,"When it hit and run, then the word ""accident"" ...",0.0,0.0,0.0,0.000000,0.0,0.0,0.000000
...,...,...,...,...,...,...,...,...
1068580,"Ken_Conklin, You have your views about churche...",0.0,0.0,0.0,0.000000,0.0,0.0,0.000000
1068581,"Too lenient. Considering her crimes, Mansfield...",0.0,0.0,0.0,0.000000,0.0,0.0,0.000000
1068582,Congratulations Elvi! I know you will do us p...,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000
1068583,"""The problem appears real, and not confined to...",0.0,0.0,0.0,0.000000,0.0,0.0,0.000000
1068584,The postman was white?,0.0,0.0,0.0,0.000000,0.0,0.0,0.000000

In [49]:
train_df[(train_df['toxicity']>=0.5) & (train_df['identity_attack'] < 0.

,comment_text,severe_toxicity,obscene,threat,insult,identity_attack,sexual_explicit,toxicity
8,There's currently a skills shortage problem in...,0.000000,0.400000,0.000000,0.400000,0.200000,0.000000,0.600000
15,Does the Magna Carta also require that Western...,0.000000,0.300000,0.000000,0.500000,0.000000,0.000000,0.700000
22,You seem to be ignorant of the fact that the I...,0.000000,0.000000,0.000000,0.600000,0.200000,0.000000,0.600000
25,Newsflash....the 2nd Amendment does not apply ...,0.000000,0.035088,0.000000,0.701754,0.017544,0.000000,0.684211
40,"""Gardner, speaking to KMGH-Channel 7, also sai...",0.000000,0.000000,0.000000,0.600000,0.000000,0.000000,0.600000
...,...,...,...,...,...,...,...,...
1068485,If you really put some thought into your post ...,0.000000,0.000000,0.000000,0.600000,0.000000,0.000000,0.600000
1068494,Because you are that stupid.,0.026316,0.131579,0.000000,0.921053,0.000000,0.000000,0.973684
1068512,"Roy Moore, Strong candidate for most disgustin...",0.100000,0.000000,0.000000,0.500000,0.000000,0.000000,0.500000
1068518,"Plainthinker, being the parasite that he is I ...",0.032787,0.114754,0.000000,0.737705,0.000000,0.016393,0.754098
1068566,Whoever thinks this should have been handled d...,0.028571,0.128571,0.085714,0.485714,0.028571,0.000000,0.500000

array([0, 1])

# 1. 테스트 분류 기준 (0.5)

In [12]:
train[(train['toxicity'] >= 0.5) & (train['identity_attack'] >= 0.5)]['comment_text'][168]

"Remember when the gay lobby said they weren't interested in appealing to children.  Who actually believed their b.s.?"

In [13]:
train[(train['toxicity'] >= 0.5) & (train['identity_attack'] >= 0.5)]['comment_text']

168        Remember when the gay lobby said they weren't ...
529        That's a distinction without a difference, giv...
583        Black folks are hunted by the police, whether ...
602        What I fail to understand is how calling someo...
633        Gay baiting is OK if a liberal does it. Otherw...
                                 ...
1068242    "It discriminates against muslims".\nThe tempo...
1068290    Trust me. it is no privilege being white with ...
1068353    An excellent way to undermine families is to s...
1068363    And what about the gross entitlement of settle...
1068514    Another angry/mentally ill white guy with a gu...
Name: comment_text, Length: 9826, dtype: object

In [14]:
train[(train['toxicity'] >= 0.5) & (train['identity_attack'] >= 0.5)]['comment_text'][529]

'That\'s a distinction without a difference, given that the Church\'s sex abuse scandal was overwhelmingly a story of men raping boys.\n\nWhatever the "experts" are claiming, as a straight man in a straight world, I can assure you that my fellow straight men, when we get "lonely," do not seek out young boys to satisfy our desires.\n\nNot all gay men do that.  But only gay men do that.  Therefore, Benedict is absolutely right to exclude them from seminaries.   Less gay men in priesthood, less risk of boys being raped by priests.'

In [18]:
train[(train['toxicity'] >= 0.5) & (train['identity_attack'] == 0)]['comment_text'][40]

'"Gardner, speaking to KMGH-Channel 7, also said that there should be a ban against traveling to North Korea"\n\nRestricting Americans ability to travel. They hate us for our freedoms. Pigs can fly.'

In [30]:
train.iloc[529,:]

id                                                                             529
comment_text                     That's a distinction without a difference, giv...
toxicity                                                                       0.7
severe_toxicity                                                                0.0
obscene                                                                        0.0
threat                                                                         0.0
insult                                                                         0.2
identity_attack                                                                0.6
sexual_explicit                                                                0.5
female                                                                         0.0
male                                                                           1.0
christian                                                                      0.1
white                                                                          0.0
muslim                                                                         0.0
black                                                                          0.0
homosexual_gay_or_lesbian                                                      0.8
jewish                                                                         0.0
psychiatric_or_mental_illness                                                  0.0
asian                                                                          0.0
Name: 529, dtype: object

In [31]:
train[train['obscene'] >=0.5]

,id,comment_text,toxicity,severe_toxicity,obscene,threat,insult,identity_attack,sexual_explicit,female,male,christian,white,muslim,black,homosexual_gay_or_lesbian,jewish,psychiatric_or_mental_illness,asian
115,115,"As she should be ! Since Obama, Oil has become...",0.700000,0.100000,0.600000,0.100000,0.300000,0.100000,0.300000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
364,364,"You're unfailingly bad at deflection, ( PeeWee...",0.714286,0.000000,0.628571,0.014286,0.642857,0.000000,0.014286,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
439,439,"There are lies, damned lies, and statistics. T...",0.700000,0.100000,0.700000,0.000000,0.300000,0.200000,0.000000,0.833333,0.833333,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
624,624,How exactly is pointing out the glaring media ...,0.600000,0.100000,0.500000,0.100000,0.600000,0.400000,0.000000,0.300000,0.200000,0.0,0.9,0.0,0.7,0.0,0.0,0.0,0.0
777,777,Murkowski only came out against the bill once ...,0.600000,0.000000,0.500000,0.000000,0.400000,0.000000,0.300000,0.300000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1068068,1068068,"Michael Gerson, another damn traitor to Ameria...",0.828125,0.171875,0.718750,0.000000,0.812500,0.031250,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1068208,1068208,THERE IS NO WAY TO STOP POLICE WHO ARE TRIGGER...,1.000000,0.166667,1.000000,0.000000,0.833333,0.166667,0.000000,0.250000,1.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1068226,1068226,"Wtf?\n\nThe lead paragraph says a ""teenage dri...",0.500000,0.200000,0.600000,0.000000,0.100000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1068334,1068334,Take your head out of your ass. We need to do ...,0.828947,0.131579,0.657895,0.000000,0.605263,0.486842,0.657895,0.000000,0.000000,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1068437,1068437,Eat. Less. Crap.,0.787500,0.062500,0.712500,0.000000,0.412500,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
train.iloc[439,:]['comment_text']

"There are lies, damned lies, and statistics. There is no gender pay gap. Women get paid the same as men when doing the same jobs with the same seniority. However, if you examine what women and men take in university - where women outnumber men - you'll find that, overwhelmingly, female students choose the soft sciences and liberal arts. Where are they outnumbered? Engineering, computer sciences, and other 'non people skill' programs. And these programs just happen to be much higher paying, on average than say sociology or psychology. or English Literature. Too bad, so sad. Likewise, women in professions don't, on average, put in the same time as men. They care more about their families (for which, kudos to them) than climbing the greasy corporate ladder. Their reward is a better life, and fewer promotions. I'd take that bargain myself, to be honest."

In [34]:
train.iloc[439,:]

id                                                                             439
comment_text                     There are lies, damned lies, and statistics. T...
toxicity                                                                       0.7
severe_toxicity                                                                0.1
obscene                                                                        0.7
threat                                                                         0.0
insult                                                                         0.3
identity_attack                                                                0.2
sexual_explicit                                                                0.0
female                                                                    0.833333
male                                                                      0.833333
christian                                                                      0.0
white                                                                          0.0
muslim                                                                         0.0
black                                                                          0.0
homosexual_gay_or_lesbian                                                      0.0
jewish                                                                         0.0
psychiatric_or_mental_illness                                                  0.0
asian                                                                          0.0
Name: 439, dtype: object

In [35]:
test.head()

   id                                       comment_text
0   0  Not me - I've seen investigations into trainin...
1   1  She was fully deportable and I am glad someone...
2   2                   That's for the courts to decide.
3   3  When she was a scrawny 11-year-old, Sherry Joh...
4   4  I cannot help but wonder what Mueller is findi...

In [1]:
import pandas as pd


tmp = pd.read_csv("prepro_train.csv")

tmp.head()

,id,comment_text,toxicity,severe_toxicity,obscene,threat,insult,identity_attack,sexual_explicit,female,male,christian,white,muslim,black,homosexual_gay_or_lesbian,jewish,psychiatric_or_mental_illness,asian
0,0,"['no', 'we', 'need', 'trump', 'to', 'stay', 'i...",0.166667,0.0,0.0,0.0,0.166667,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,"['wow', 'precious']",0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,"['haven', 't', 'been', 'here', 'when', 'the', ...",0.200000,0.0,0.0,0.2,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,['baloney'],0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,"['when', 'it', 'hit', 'and', 'run', 'then', 't...",0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
IDENTITY_COLMUNS = [
    'female','male', 'christian', 'white', 'muslim', 'black',
    'homosexual_gay_or_lesbian', 'jewish', 'psychiatric_or_mental_illness', 'asian'
]

In [40]:
from sklearn import metrics
import numpy as np

SUBGROUP_AUC = 'subgroup_auc'
BPSN_AUC = 'bpsn_auc'  # stands for background positive, subgroup negative
BNSP_AUC = 'bnsp_auc'  # stands for background negative, subgroup positive

def compute_auc(y_true_proba, y_pred_proba):
    try:
        return metrics.roc_auc_score(y_true_proba >= 0.5, y_pred_proba >= 0.5)
    except ValueError:
        return np.nan

def compute_subgroup_auc(df, subgroup_col, true_col, pred_col):
    subgroup_indices = df[subgroup_col] >= 0.5
    subgroup_examples = df[subgroup_indices]
    
    return compute_auc(subgroup_examples[true_col], subgroup_examples[pred_col])

def compute_bpsn_auc(df, subgroup_col, true_col, pred_col):
    """Computes the AUC of the within-subgroup negative examples and the background positive examples."""
    subgroup_indices = df[subgroup_col] >= 0.5
    label_indices = df[true_col] >= 0.5
    
    subgroup_negative_examples = df[subgroup_indices & ~label_indices]
    non_subgroup_positive_examples = df[~subgroup_indices & label_indices]
    examples = pd.concat([subgroup_negative_examples, non_subgroup_positive_examples], axis=0)
    
    return compute_auc(examples[true_col], examples[pred_col])

def compute_bnsp_auc(df, subgroup_col, true_col, pred_col):
    """Computes the AUC of the within-subgroup positive examples and the background negative examples."""
    subgroup_indices = df[subgroup_col] >= 0.5
    label_indices = df[true_col] >= 0.5
                                        
    subgroup_positive_examples = df[subgroup_indices & label_indices]
    non_subgroup_negative_examples = df[~subgroup_indices & ~label_indices]
    examples = pd.concat([subgroup_positive_examples, non_subgroup_negative_examples], axis=0)
    return compute_auc(examples[true_col], examples[pred_col])

def compute_bias_metrics_for_model(dataset, subgroups, true_col = "toxicity", pred_col = "predict"):
    """Computes per-subgroup metrics for all subgroups and one model."""
    records = []
    for subgroup in subgroups:
        record = {
            'subgroup': subgroup,
            'subgroup_size': (dataset[subgroup] >= 0.5).sum()
        }
        record[SUBGROUP_AUC] = compute_subgroup_auc(dataset, subgroup, true_col, pred_col)
        record[BPSN_AUC] = compute_bpsn_auc(dataset, subgroup, true_col, pred_col)
        record[BNSP_AUC] = compute_bnsp_auc(dataset, subgroup, true_col, pred_col)
        records.append(record)

    return pd.DataFrame(records).sort_values('subgroup_auc', ascending=True)

# bias_metrics_df = compute_bias_metrics_for_model(val_dataset, IDENTITY_COLMUNS)
# bias_metrics_df

In [41]:
check_sub_background = pd.read_csv('submit_Background.csv')
check_sub_all = pd.read_csv('submit_dat1.csv')

In [ ]:
bias_metrics_bg = compute_bias_metrics_for_model(check_sub_background, IDENTITY_COLMUNS)
bias_metrics_bg

In [45]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1068585 entries, 0 to 1068584
Data columns (total 19 columns):
 #   Column                         Non-Null Count    Dtype
---  ------                         --------------    -----
 0   id                             1068585 non-null  int64
 1   comment_text                   1068585 non-null  object
 2   toxicity                       1068585 non-null  float64
 3   severe_toxicity                1068585 non-null  float64
 4   obscene                        1068585 non-null  float64
 5   threat                         1068585 non-null  float64
 6   insult                         1068585 non-null  float64
 7   identity_attack                1068585 non-null  float64
 8   sexual_explicit                1068585 non-null  float64
 9   female                         318970 non-null   float64
 10  male                           318970 non-null   float64
 11  christian                      318970 non-null   float64
 12  white                          318970 non-null   float64
 13  muslim                         318970 non-null   float64
 14  black                          318970 non-null   float64
 15  homosexual_gay_or_lesbian      318970 non-null   float64
 16  jewish                         318970 non-null   float64
 17  psychiatric_or_mental_illness  318970 non-null   float64
 18  asian                          318970 non-null   float64
dtypes: float64(17), int64(1), object(1)
memory usage: 154.9+ MB

1. Background 데이터만 사용해서 학습을 하고 -> subgroup toxicity label채우기 
1-1. label채우고 전체 데이터를 학습 -> Test label 제출

2. identity를 언급한 데이터(318970)를 가지고 학습 (toxicity, IDENTITY_COL) -> 없는 데이터 채우기 
2-1. 전체를 다 채운 데이터로 training -> Test 제출

In [51]:
subgroup = train[(train['female'] >= 0.5) | (train['male'] >= 0.5) | (train['christian'] >= 0.5) | (train['white'] >= 0.5) | (train['muslim'] >= 0.5) | (train['black'] >= 0.5) | (train['homosexual_gay_or_lesbian'] >= 0.5) | (train['jewish'] >= 0.5) | (train['psychiatric_or_mental_illness'] >= 0.5) | (train['asian'] >= 0.5)]
subgroup

,id,comment_text,toxicity,severe_toxicity,obscene,threat,insult,identity_attack,sexual_explicit,female,male,christian,white,muslim,black,homosexual_gay_or_lesbian,jewish,psychiatric_or_mental_illness,asian
11,11,"Well, when you consider the success of Playboy...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000
22,22,You seem to be ignorant of the fact that the I...,0.6,0.0,0.0,0.0,0.6,0.2,0.0,0.4,0.000000,0.0,0.000000,0.9,0.0,0.0,0.0,0.0,0.000000
37,37,What do Christians have to do with this articl...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,1.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000
59,59,Hillary will meet the requirements of her fund...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.6,0.100000,0.0,0.000000,0.0,0.0,0.2,0.0,0.0,0.000000
66,66,"Many couples incorporate the above mentioned ""...",0.1,0.0,0.1,0.0,0.0,0.0,0.2,0.0,0.700000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1068545,1068545,"In a recent highly publicised case, the man in...",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000
1068546,1068546,https://www.youtube.com/watch?v=Qup47XJGIl4\n\...,0.3,0.0,0.0,0.2,0.1,0.1,0.0,0.0,1.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000
1068556,1068556,Liu Xiaobo is too famous. If he was able to tr...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.5,0.0,0.0,0.0,0.833333
1068572,1068572,Well aren't you our Debbie Downer? You must be...,0.2,0.0,0.0,0.0,0.2,0.0,0.0,1.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000
1068584,1068584,The postman was white?,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.166667,0.0,0.833333,0.0,0.0,0.0,0.0,0.0,0.000000

In [5]:
check = pd.read_csv("make_train.csv")

check.head()

,id,comment_text,toxicity,severe_toxicity,obscene,threat,insult,identity_attack,sexual_explicit,female,male,christian,white,muslim,black,homosexual_gay_or_lesbian,jewish,psychiatric_or_mental_illness,asian
0,0,"No, we need Trump to stay in so he can lose.",0.166667,0.0,0.0,0.0,0.166667,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Wow. Precious.,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Haven't been here when the oil economy dead ha...,0.200000,0.0,0.0,0.2,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,'\nBaloney.,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,"When it hit and run, then the word ""accident"" ...",0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
check.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1068585 entries, 0 to 1068584
Data columns (total 19 columns):
 #   Column                         Non-Null Count    Dtype
---  ------                         --------------    -----
 0   id                             1068585 non-null  int64
 1   comment_text                   1068585 non-null  object
 2   toxicity                       1068585 non-null  float64
 3   severe_toxicity                1068585 non-null  float64
 4   obscene                        1068585 non-null  float64
 5   threat                         1068585 non-null  float64
 6   insult                         1068585 non-null  float64
 7   identity_attack                1068585 non-null  float64
 8   sexual_explicit                1068585 non-null  float64
 9   female                         187877 non-null   float64
 10  male                           187877 non-null   float64
 11  christian                      187877 non-null   float64
 12  white                          187877 non-null   float64
 13  muslim                         187877 non-null   float64
 14  black                          187877 non-null   float64
 15  homosexual_gay_or_lesbian      187877 non-null   float64
 16  jewish                         187877 non-null   float64
 17  psychiatric_or_mental_illness  187877 non-null   float64
 18  asian                          187877 non-null   float64
dtypes: float64(17), int64(1), object(1)
memory usage: 154.9+ MB

In [6]:
import csv
data = pd.read_csv('add_identity_train.csv', quoting=csv.QUOTE_NONE)

In [8]:
tmp = data[['identity_attack','identity']]

In [10]:
tmp[(tmp['identity_attack'] >= 0.5)]

         identity_attack  identity
2063            0.500000       NaN
2112            0.776316  0.001107
2290            0.500000  0.001579
3360            0.550000  0.005138
3822            0.600000       NaN
...                  ...       ...
1019771         0.500000  0.000978
1019983         0.700000  0.002137
1020530         0.500000  0.001383
1020735         0.500000       NaN
1020783         0.500000  0.050234

[1140 rows x 2 columns]

In [6]:
train_na = train.dropna()
train_dd = train[~train.index.isin(train_na.index)]

In [9]:
train_dd = train_dd[col]

In [10]:
train_na = train_na[col]

In [23]:
mix = pd.concat([train_dd,train_na], axis=0)
mix = mix.sort_index()

In [27]:
mix = mix.fillna(1)

In [28]:
mix

,female,male,christian,white,muslim,black,homosexual_gay_or_lesbian,jewish,psychiatric_or_mental_illness,asian
0,1.0,1.000000,1.0,1.000000,1.0,1.0,1.0,1.0,1.0,1.0
1,1.0,1.000000,1.0,1.000000,1.0,1.0,1.0,1.0,1.0,1.0
2,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
4,1.0,1.000000,1.0,1.000000,1.0,1.0,1.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...
1068580,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
1068581,1.0,1.000000,1.0,1.000000,1.0,1.0,1.0,1.0,1.0,1.0
1068582,1.0,1.000000,1.0,1.000000,1.0,1.0,1.0,1.0,1.0,1.0
1068583,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
1068584,0.0,0.166667,0.0,0.833333,0.0,0.0,0.0,0.0,0.0,0.0

In [24]:
col = ['female',
       'male', 'christian', 'white', 'muslim', 'black',
       'homosexual_gay_or_lesbian', 'jewish', 'psychiatric_or_mental_illness',
       'asian']

In [30]:
train_fill = mix.join(train[['toxicity']], how='left')

In [32]:
cols = train_fill.columns.tolist()
cols = [cols[-1]] + cols[:-1]
train_fill = train_fill[cols]
train_fill

,toxicity,female,male,christian,white,muslim,black,homosexual_gay_or_lesbian,jewish,psychiatric_or_mental_illness,asian
0,0.166667,1.0,1.000000,1.0,1.000000,1.0,1.0,1.0,1.0,1.0,1.0
1,0.000000,1.0,1.000000,1.0,1.000000,1.0,1.0,1.0,1.0,1.0,1.0
2,0.200000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
3,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
4,0.000000,1.0,1.000000,1.0,1.000000,1.0,1.0,1.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
1068580,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
1068581,0.000000,1.0,1.000000,1.0,1.000000,1.0,1.0,1.0,1.0,1.0,1.0
1068582,0.000000,1.0,1.000000,1.0,1.000000,1.0,1.0,1.0,1.0,1.0,1.0
1068583,0.000000,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
1068584,0.000000,0.0,0.166667,0.0,0.833333,0.0,0.0,0.0,0.0,0.0,0.0

In [20]:
train

,id,comment_text,toxicity,severe_toxicity,obscene,threat,insult,identity_attack,sexual_explicit,female,male,christian,white,muslim,black,homosexual_gay_or_lesbian,jewish,psychiatric_or_mental_illness,asian
0,0,"No, we need Trump to stay in so he can lose.",0.166667,0.0,0.0,0.0,0.166667,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Wow. Precious.,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,Haven't been here when the oil economy dead ha...,0.200000,0.0,0.0,0.2,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
3,3,'\nBaloney.,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
4,4,"When it hit and run, then the word ""accident"" ...",0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1068580,1068580,"Ken_Conklin, You have your views about churche...",0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
1068581,1068581,"Too lenient. Considering her crimes, Mansfield...",0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1068582,1068582,Congratulations Elvi! I know you will do us p...,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1068583,1068583,"""The problem appears real, and not confined to...",0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
1068584,1068584,The postman was white?,0.000000,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.166667,0.0,0.833333,0.0,0.0,0.0,0.0,0.0,0.0